name: deploy project to EC2

on:
  push:
    branches: [main]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 (git pull → build → restart)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "[DEBUG][SSH] ✅ SSH 연결 성공"

            [ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh"
            echo "[DEBUG][NVM] ✅ NVM 로드 완료"

            # (EC2에 1회 적용) 스왑 2GB
            if ! sudo swapon --show | grep -q '/swapfile'; then
              echo "[DEBUG][SWAP] ⌛ 스왑 생성 진행 중..."
              sudo fallocate -l 2G /swapfile || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
              sudo chmod 600 /swapfile
              sudo mkswap /swapfile
              sudo swapon /swapfile
              echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
              echo "[DEBUG][SWAP] ✅ 스왑 생성 완료"
            else
              echo "[DEBUG][SWAP] ✅ 스왑 이미 존재함"
            fi

            cd "${{ secrets.EC2_APP_DIR }}"
            echo "[DEBUG][DIR] ✅ 현재 디렉토리: $(pwd)"

            # 최신 코드 가져오기
            echo "[DEBUG][GIT] ⌛ Git fetch & reset 진행 중..."
            git fetch --all
            git reset --hard origin/main
            echo "[DEBUG][GIT] ✅ Git 최신화 완료"

            # 환경 변수 파일 생성
            echo "[DEBUG][ENV] ⌛ .env 파일 생성 진행 중..."
            cat > .env <<EOF
            NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_JS_KEY_KAKAO: ${{ secrets.NEXT_PUBLIC_JS_KEY_KAKAO }}
            EOF
            echo "[DEBUG][ENV] ✅ .env 파일 생성 완료"

            # 빌드
            echo "[DEBUG][NPM] ⌛ 의존성 설치 진행 중..."
            HUSKY=0 npm ci
            echo "[DEBUG][NPM] ✅ 의존성 설치 완료"

            echo "[DEBUG][BUILD] ⌛ 빌드 진행 중..."
            NODE_ENV=production npm run build
            echo "[DEBUG][BUILD] ✅ 빌드 완료"

            # 빌드 산출물만 남기고 소스코드/불필요한 파일 삭제
            echo "[DEBUG][CLEANUP] ⌛ 불필요 파일 삭제 진행 중..."
            find . -mindepth 1 -maxdepth 1 \
              ! -name '.git' \
              ! -name '.next' \
              ! -name 'node_modules' \
              ! -name 'package.json' \
              ! -name 'package-lock.json' \
              -exec rm -rf {} +
            echo "[DEBUG][CLEANUP] ✅ 불필요 파일 삭제 완료"

            # PM2 재시작
            echo "[DEBUG][PM2] ⌛ PM2 재시작 진행 중..."
            pm2 describe project-final-app > /dev/null \
              && pm2 reload project-final-app \
              || pm2 start "npm run start" --name "project-final-app"
            pm2 save
            echo "[DEBUG][PM2] ✅ PM2 재시작 완료"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CloudFront Invalidate Cache
        run: |
          echo "[DEBUG][CF] ⌛ CloudFront 캐시 무효화 진행 중..."
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          echo "[DEBUG][CF] ✅ CloudFront 캐시 무효화 완료"
