name: deploy project to EC2

on:
  push:
    branches: [main]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      # 1) 저장소 체크아웃
      - name: Git Checkout
        uses: actions/checkout@v4

      # 2) Node 환경 세팅
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      # 3) 빌드
      - name: Install dependencies & Build
        run: |
          HUSKY=0 npm ci
          NODE_ENV=production npm run build

      # 4) 배포 패키징 (필요 파일만 압축)
      - name: Package build artifacts
        run: |
          tar -czf app.tar.gz .next public package.json node_modules

      # 5) EC2로 전송
      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'app.tar.gz'
          target: '${{ secrets.EC2_APP_DIR }}'

      # 6) EC2에서 압축 해제 & 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd "${{ secrets.EC2_APP_DIR }}"

            # 기존 파일 삭제
            rm -rf .next public package.json node_modules

            # 새 빌드 압축 해제
            tar -xzf app.tar.gz
            rm app.tar.gz

            # PM2 재시작
            pm2 reload project-final-app || pm2 start "npm run start" --name "project-final-app"
            pm2 save

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CloudFront Invalidate Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
