name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Cleanup Preview Environment on EC2
        run: |
          echo "[DEBUG][GHA] ⏳ EC2 접속 후 preview 정리 작업 실행..."
          ssh -o StrictHostKeyChecking=no ubuntu@"${{ secrets.EC2_HOST }}" bash -se <<'EOSSH'
          set -euo pipefail

          # === GitHub Actions 값 주입 (여기서 GH 컨텍스트는 이미 치환된 문자열이 됨) ===
          BRANCH="${{ github.event.pull_request.head.ref }}"
          SANITIZED="$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed 's#[^a-z0-9._-]#-#g')"
          DOMAIN="${{ vars.DOMAIN }}"
          APP_DIR="/var/www/preview/${SANITIZED}"
          CONF_FILE="/etc/nginx/conf.d/preview-${SANITIZED}.conf"

          echo "[INFO] 🧹 Cleaning preview for branch: ${SANITIZED}"

          # 1) PM2 프로세스 정리
          echo "[DEBUG][EC2] ⏳ PM2 프로세스 삭제 중...: preview-${SANITIZED}"
          pm2 delete "preview-${SANITIZED}" || true
          pm2 save
          echo "[DEBUG][EC2] ✅ PM2 프로세스 삭제 완료"

          # 2) 디렉토리 정리
          if [ -d "$APP_DIR" ]; then
            echo "[DEBUG][EC2] ⏳ 앱 디렉토리 삭제중...: $APP_DIR"
            sudo rm -rf "$APP_DIR"
            echo "[DEBUG][EC2] ✅ 앱 디렉토리 삭제 완료"
          fi

          # 3) Nginx 설정 제거
          if [ -f "$CONF_FILE" ]; then
            echo "[DEBUG][EC2] ⏳ Nginx conf 삭제중...: $CONF_FILE"
            sudo rm -f "$CONF_FILE"
            sudo nginx -t
            sudo systemctl reload nginx || sudo nginx -s reload
            echo "[DEBUG][EC2] ✅ Nginx conf 삭제 완료"
          fi

          echo "[INFO] ✅ Cleanup finished for branch: ${SANITIZED}"
          EOSSH
