name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Compute branch name
        id: meta
        run: |
          RAW="${{ github.event.pull_request.head.ref }}"
          SANITIZED="$(echo "$RAW" | tr '[:upper:]' '[:lower:]' | sed 's#[^a-z0-9._-]#-#g')"
          echo "name=$SANITIZED" >> $GITHUB_OUTPUT

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Cleanup Preview Environment on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DOMAIN: ${{ vars.DOMAIN }}
          BRANCH: ${{ steps.meta.outputs.name }}
        run: |
          echo "[DEBUG][GHA] ⏳ EC2 접속 후 preview 정리 작업 실행..."
          ssh -o StrictHostKeyChecking=no ubuntu@"${EC2_HOST}" bash -se <<'EOSSH'
          set -euo pipefail
          BRANCH="${BRANCH}"
          APP_DIR="/var/www/preview/${BRANCH}"
          CONF_FILE="/etc/nginx/conf.d/preview-${BRANCH}.conf"

          echo "[INFO] 🧹 Cleaning preview for branch: ${BRANCH}"

          # 1) PM2 프로세스 정리
          echo "[DEBUG][EC2] ⏳ PM2 프로세스 삭제 중...: preview-${BRANCH}"
          pm2 delete "preview-${BRANCH}" || true
          pm2 save
          echo "[DEBUG][EC2] ✅ PM2 프로세스 삭제 완료"

          # 2) 디렉토리 정리
          if [ -d "$APP_DIR" ]; then
            echo "[DEBUG][EC2] ⏳ 앱 디렉토리 삭제중...: $APP_DIR"
            sudo rm -rf "$APP_DIR"
            echo "[DEBUG][EC2] ✅ 앱 디렉토리 삭제 완료"
          fi

          # 3) Nginx 설정 제거
          if [ -f "$CONF_FILE" ]; then
            echo "[DEBUG][EC2] ⏳ Nginx conf 삭제중...: $CONF_FILE"
            sudo rm -f "$CONF_FILE"
            sudo nginx -t
            sudo systemctl reload nginx || sudo nginx -s reload
            echo "[DEBUG][EC2] ✅ Nginx conf 삭제 완료"
          fi

          echo "[INFO] ✅ Cleanup finished for branch: ${BRANCH}"
          EOSSH
